# Generated by Django 5.1.2 on 2024-11-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuciorder',
            name='debt',
            field=models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Lunas', 'Lunas')], default='Belum Bayar', max_length=20),
        ),
    ]
